language: node_js
node_js:
  - "8"
dist: trusty
services:
  - mongodb
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - yarn install
  - yarn build
  - yarn install-client
script:
  - sleep 3
  - yarn test
  - cd client/
  - yarn test
